--
-- PostgreSQL database dump
--

\restrict SpcPElaH5rxwEA16efw4ak4OaoE5FG9hyZnjWedc5oUq8I16FUx7hKQs8RbLWzn

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-13 22:08:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 228 (class 1259 OID 16434)
-- Name: Avisos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Avisos" (
                                 id_aviso integer NOT NULL,
                                 id_tarea integer NOT NULL,
                                 id_usuario integer NOT NULL,
                                 mensaje text NOT NULL,
                                 leido boolean NOT NULL,
                                 fecha_generacion timestamp without time zone NOT NULL
);


ALTER TABLE public."Avisos" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16433)
-- Name: Avisos_id_aviso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Avisos" ALTER COLUMN id_aviso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Avisos_id_aviso_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16448)
-- Name: Calificaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Calificaciones" (
                                         id_calificacion integer NOT NULL,
                                         id_usuario integer NOT NULL,
                                         id_materia integer NOT NULL,
                                         nota numeric(4,2) NOT NULL
);


ALTER TABLE public."Calificaciones" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16447)
-- Name: Calificaciones_id_calificacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Calificaciones" ALTER COLUMN id_calificacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Calificaciones_id_calificacion_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16409)
-- Name: Horario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Horario" (
                                  id_horario integer NOT NULL,
                                  id_materia integer NOT NULL,
                                  dia_semana character varying(20) NOT NULL,
                                  hora_inicio time without time zone NOT NULL,
                                  hora_fin time without time zone NOT NULL,
                                  aula character varying(50)
);


ALTER TABLE public."Horario" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16408)
-- Name: Horario_id_horario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Horario" ALTER COLUMN id_horario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Horario_id_horario_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16401)
-- Name: Materia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Materia" (
                                  id_materia integer NOT NULL,
                                  nombre character varying(100) NOT NULL
);


ALTER TABLE public."Materia" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16400)
-- Name: Materia_id_materia_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Materia" ALTER COLUMN id_materia ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Materia_id_materia_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16458)
-- Name: Mensajes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Mensajes" (
                                   id_mensaje integer NOT NULL,
                                   id_usuario integer NOT NULL,
                                   contenido text NOT NULL,
                                   tipo character varying(20) NOT NULL,
                                   fecha_envio timestamp without time zone NOT NULL
);


ALTER TABLE public."Mensajes" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16457)
-- Name: Mensajes_id_mensaje_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Mensajes" ALTER COLUMN id_mensaje ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Mensajes_id_mensaje_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16471)
-- Name: Respuestas_bot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Respuestas_bot" (
                                         id_respuesta integer NOT NULL,
                                         palabra_clave character varying(100) NOT NULL,
                                         respuesta text NOT NULL,
                                         activo boolean
);


ALTER TABLE public."Respuestas_bot" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16470)
-- Name: Respuestas_bot_id_respuesta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Respuestas_bot" ALTER COLUMN id_respuesta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Respuestas_bot_id_respuesta_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16482)
-- Name: Sesiones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sesiones" (
                                   id_sesion integer NOT NULL,
                                   id_usuario integer,
                                   token character varying(255) NOT NULL,
                                   fecha_inicio timestamp without time zone,
                                   fecha_fin timestamp without time zone
);


ALTER TABLE public."Sesiones" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16481)
-- Name: Sesiones_id_sesion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sesiones" ALTER COLUMN id_sesion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sesiones_id_sesion_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16420)
-- Name: Tareas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tareas" (
                                 id_tarea integer NOT NULL,
                                 id_materia integer NOT NULL,
                                 id_usuario integer NOT NULL,
                                 titulo character varying(200) NOT NULL,
                                 descripcion text NOT NULL,
                                 fecha_entrega date NOT NULL
);


ALTER TABLE public."Tareas" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16419)
-- Name: Tareas_id_tarea_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tareas" ALTER COLUMN id_tarea ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tareas_id_tarea_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: Usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Usuarios" (
                                   id_usuario integer NOT NULL,
                                   nombre character varying(100) NOT NULL,
                                   email character varying(255) NOT NULL,
                                   "contraseña" character varying(100) NOT NULL,
                                   rol character varying(20) NOT NULL,
                                   fecha_registro timestamp without time zone
);


ALTER TABLE public."Usuarios" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: Usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Usuarios" ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Usuarios_id_usuario_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4978 (class 0 OID 16434)
-- Dependencies: 228
-- Data for Name: Avisos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Avisos" (id_aviso, id_tarea, id_usuario, mensaje, leido, fecha_generacion) FROM stdin;
\.


--
-- TOC entry 4980 (class 0 OID 16448)
-- Dependencies: 230
-- Data for Name: Calificaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Calificaciones" (id_calificacion, id_usuario, id_materia, nota) FROM stdin;
\.


--
-- TOC entry 4974 (class 0 OID 16409)
-- Dependencies: 224
-- Data for Name: Horario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Horario" (id_horario, id_materia, dia_semana, hora_inicio, hora_fin, aula) FROM stdin;
\.


--
-- TOC entry 4972 (class 0 OID 16401)
-- Dependencies: 222
-- Data for Name: Materia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Materia" (id_materia, nombre) FROM stdin;
\.


--
-- TOC entry 4982 (class 0 OID 16458)
-- Dependencies: 232
-- Data for Name: Mensajes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Mensajes" (id_mensaje, id_usuario, contenido, tipo, fecha_envio) FROM stdin;
\.


--
-- TOC entry 4984 (class 0 OID 16471)
-- Dependencies: 234
-- Data for Name: Respuestas_bot; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Respuestas_bot" (id_respuesta, palabra_clave, respuesta, activo) FROM stdin;
\.


--
-- TOC entry 4986 (class 0 OID 16482)
-- Dependencies: 236
-- Data for Name: Sesiones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sesiones" (id_sesion, id_usuario, token, fecha_inicio, fecha_fin) FROM stdin;
\.


--
-- TOC entry 4976 (class 0 OID 16420)
-- Dependencies: 226
-- Data for Name: Tareas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tareas" (id_tarea, id_materia, id_usuario, titulo, descripcion, fecha_entrega) FROM stdin;
\.


--
-- TOC entry 4970 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: Usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Usuarios" (id_usuario, nombre, email, "contraseña", rol, fecha_registro) FROM stdin;
\.


--
-- TOC entry 4992 (class 0 OID 0)
-- Dependencies: 227
-- Name: Avisos_id_aviso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Avisos_id_aviso_seq"', 1, false);


--
-- TOC entry 4993 (class 0 OID 0)
-- Dependencies: 229
-- Name: Calificaciones_id_calificacion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Calificaciones_id_calificacion_seq"', 1, false);


--
-- TOC entry 4994 (class 0 OID 0)
-- Dependencies: 223
-- Name: Horario_id_horario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Horario_id_horario_seq"', 1, false);


--
-- TOC entry 4995 (class 0 OID 0)
-- Dependencies: 221
-- Name: Materia_id_materia_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Materia_id_materia_seq"', 1, false);


--
-- TOC entry 4996 (class 0 OID 0)
-- Dependencies: 231
-- Name: Mensajes_id_mensaje_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Mensajes_id_mensaje_seq"', 1, false);


--
-- TOC entry 4997 (class 0 OID 0)
-- Dependencies: 233
-- Name: Respuestas_bot_id_respuesta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Respuestas_bot_id_respuesta_seq"', 1, false);


--
-- TOC entry 4998 (class 0 OID 0)
-- Dependencies: 235
-- Name: Sesiones_id_sesion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sesiones_id_sesion_seq"', 1, false);


--
-- TOC entry 4999 (class 0 OID 0)
-- Dependencies: 225
-- Name: Tareas_id_tarea_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tareas_id_tarea_seq"', 1, false);


--
-- TOC entry 5000 (class 0 OID 0)
-- Dependencies: 219
-- Name: Usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Usuarios_id_usuario_seq"', 1, false);


--
-- TOC entry 4804 (class 2606 OID 16446)
-- Name: Avisos Avisos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Avisos"
    ADD CONSTRAINT "Avisos_pkey" PRIMARY KEY (id_aviso);


--
-- TOC entry 4806 (class 2606 OID 16456)
-- Name: Calificaciones Calificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Calificaciones"
    ADD CONSTRAINT "Calificaciones_pkey" PRIMARY KEY (id_calificacion);


--
-- TOC entry 4800 (class 2606 OID 16418)
-- Name: Horario Horario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Horario"
    ADD CONSTRAINT "Horario_pkey" PRIMARY KEY (id_horario);


--
-- TOC entry 4798 (class 2606 OID 16407)
-- Name: Materia Materia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Materia"
    ADD CONSTRAINT "Materia_pkey" PRIMARY KEY (id_materia);


--
-- TOC entry 4808 (class 2606 OID 16469)
-- Name: Mensajes Mensajes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Mensajes"
    ADD CONSTRAINT "Mensajes_pkey" PRIMARY KEY (id_mensaje);


--
-- TOC entry 4810 (class 2606 OID 16480)
-- Name: Respuestas_bot Respuestas_bot_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Respuestas_bot"
    ADD CONSTRAINT "Respuestas_bot_pkey" PRIMARY KEY (id_respuesta);


--
-- TOC entry 4812 (class 2606 OID 16488)
-- Name: Sesiones Sesiones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sesiones"
    ADD CONSTRAINT "Sesiones_pkey" PRIMARY KEY (id_sesion);


--
-- TOC entry 4802 (class 2606 OID 16432)
-- Name: Tareas Tareas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tareas"
    ADD CONSTRAINT "Tareas_pkey" PRIMARY KEY (id_tarea);


--
-- TOC entry 4796 (class 2606 OID 16399)
-- Name: Usuarios Usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuarios"
    ADD CONSTRAINT "Usuarios_pkey" PRIMARY KEY (id_usuario);


--
-- TOC entry 4816 (class 2606 OID 16504)
-- Name: Avisos Avisos_id_tarea_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Avisos"
    ADD CONSTRAINT "Avisos_id_tarea_fkey" FOREIGN KEY (id_tarea) REFERENCES public."Tareas"(id_tarea);


--
-- TOC entry 4817 (class 2606 OID 16509)
-- Name: Avisos Avisos_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Avisos"
    ADD CONSTRAINT "Avisos_id_usuario_fkey" FOREIGN KEY (id_usuario) REFERENCES public."Usuarios"(id_usuario);


--
-- TOC entry 4818 (class 2606 OID 16519)
-- Name: Calificaciones Calificaciones_id_materia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Calificaciones"
    ADD CONSTRAINT "Calificaciones_id_materia_fkey" FOREIGN KEY (id_materia) REFERENCES public."Materia"(id_materia);


--
-- TOC entry 4819 (class 2606 OID 16514)
-- Name: Calificaciones Calificaciones_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Calificaciones"
    ADD CONSTRAINT "Calificaciones_id_usuario_fkey" FOREIGN KEY (id_usuario) REFERENCES public."Usuarios"(id_usuario);


--
-- TOC entry 4813 (class 2606 OID 16489)
-- Name: Horario Horario_id_materia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Horario"
    ADD CONSTRAINT "Horario_id_materia_fkey" FOREIGN KEY (id_materia) REFERENCES public."Materia"(id_materia);


--
-- TOC entry 4820 (class 2606 OID 16529)
-- Name: Mensajes Mensajes_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Mensajes"
    ADD CONSTRAINT "Mensajes_id_usuario_fkey" FOREIGN KEY (id_usuario) REFERENCES public."Usuarios"(id_usuario);


--
-- TOC entry 4821 (class 2606 OID 16524)
-- Name: Sesiones Sesiones_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sesiones"
    ADD CONSTRAINT "Sesiones_id_usuario_fkey" FOREIGN KEY (id_usuario) REFERENCES public."Usuarios"(id_usuario);


--
-- TOC entry 4814 (class 2606 OID 16494)
-- Name: Tareas Tareas_id_materia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tareas"
    ADD CONSTRAINT "Tareas_id_materia_fkey" FOREIGN KEY (id_materia) REFERENCES public."Materia"(id_materia);


--
-- TOC entry 4815 (class 2606 OID 16499)
-- Name: Tareas Tareas_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tareas"
    ADD CONSTRAINT "Tareas_id_usuario_fkey" FOREIGN KEY (id_usuario) REFERENCES public."Usuarios"(id_usuario);


-- Completed on 2026-06-13 22:08:35

--
-- PostgreSQL database dump complete
--

\unrestrict SpcPElaH5rxwEA16efw4ak4OaoE5FG9hyZnjWedc5oUq8I16FUx7hKQs8RbLWzn

